apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  razorpay-key-id: YOUR_BASE64_ENCODED_KEY
  razorpay-key-secret: YOUR_BASE64_ENCODED_SECRET
  news-api-key: YOUR_BASE64_ENCODED_API_KEY
